name: Project checker

on:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    name: Run compilation
    timeout-minutes: 2
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Run compilation
        run: |
          make

  run_tests:
    name: Run tests
    needs: compile
    timeout-minutes: 2
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          make tests_run
